### ISSUE TITLE
Add gpiote module to nrf52-hal-common

### ISSUE THREAD

**Issue by chris-ricketts** [nrf-rs/nrf-hal#120]
It would be nice to have a safe, ergonomic API to setup events and tasks using the GPIOTE module.

I have an [example](https://github.com/chris-ricketts/nrf52dk-rtfm-gpios/blob/master/src/main.rs) of how the PAC can be used directly, tested out on the nrf52 dev kit. 

I'm up for giving this a go.

I'm guessing it's going to be kind of similar to the `gpio` module but with more layers. Also I'm wondering about the best way to handle the multiple channels.

It definitely needs a typestate to indicate whether an event pin is configured as pullup or pulldown as a floating pin had me scratching my head for a while.

Does anyone have any hints or implementations they know of in other HAL crates that deal with similar functionality?

**Comment by hannobraun** [comment]
Another usage example: https://github.com/braun-embedded/rust-dw1000/blob/34df744e4d0b83602191f7a48dfd4951ec143655/dwm1001/src/lib.rs#L884

**Comment by jamesmunns** [comment]
@chris-ricketts have you made any progress on this so far?

**Comment by chris-ricketts** [comment]
@jamesmunns I haven't got round to starting this yet - would you like to take it on?

**Comment by kalkyl** [comment]
Has anyone started on this yet?
I've been using the gpiote quite a lot and have written a module to help with that. Should i open a PR with what i have where we could discuss and agree on an API?

**Comment by jonas-schievink** [comment]
@kalkyl Go ahead! I always find it easier to discuss working code rather than ideas.

**Comment by kalkyl** [comment]
PR #167 
Example:
https://github.com/kalkyl/nrf-hal/blob/gpiote/examples/gpiote-demo/src/main.rs

**Comment by jonas-schievink** [comment]
https://github.com/nrf-rs/nrf-hal/pull/167 was merged.
