### ISSUE TITLE
Move board support crates out of this repo

### ISSUE THREAD

**Issue by jonas-schievink** [nrf-rs/nrf-hal#141]
This repository should focus on HALs for the microcontrollers, not on providing support for every conceivable devboard that contributors might not have. Board specific crates should be moved to their own repository.

**Comment by jonathanpallant** [comment]
That seems reasonable.

**Comment by jonathanpallant** [comment]
I think we could do this without losing history using git-subtree?

https://dharmitshah.com/2017/10/git-subtree-new-repo/
