### ISSUE TITLE
`Pin`'s public fields let you break `Pin`'s singleton property

### ISSUE THREAD

**Issue by japaric** [nrf-rs/nrf-hal#146]
For example:

``` rust
let p0 = p0::Parts(p.P0);
let a = p0.p0_00.degrade();
let mut b = p0.p0_01.degrade();
b.pin = 0;
```

Lets you create 2 P0.00 pins. I don't think this operation is UB per se but it does break the intended (singleton) semantics and can result in IO misconfiguration, e.g. configuring P0.00 both as serial Tx and Rx if you pass the `a` and `b` from above to the `Uarte` abstraction.

Setting the public `pin` field to value equal or greater than `32` may result in out of bounds array access though (either a panic or UB if the HAL is using unchecked bounds access).

I think making the fields private and instead providing getter methods for `pin` and `port` would be a better fit here.

**Comment by jonas-schievink** [comment]
I have a fix up at https://github.com/nrf-rs/nrf-hal/pull/155
