### ISSUE TITLE
Interrupt example

### ISSUE THREAD

**Issue by dzervas** [nrf-rs/nrf-hal#197]
I'm trying to write an interrupt that let's say will fire up using `TIMER0` every second. I understand that I need something like the following function

```rust
#[interrupt]
fn hello() {
  // Do something
}
```

And call `enable_interrupt` on `TIMER0`. What I don't understand is how to tell which interrupt to fire. What happens if I add another interrupt function that I want it to fire only on `TIMER1`?

**Comment by blueluna** [comment]
The function name shall be named after the interrupt. See the following example,
https://github.com/nrf-rs/nRF52840-DK/blob/master/examples/blinky_interrupt_rtt.rs
