### ISSUE TITLE
CI breaks @ rtic-demo example

### ISSUE THREAD

**Issue by kalkyl** [nrf-rs/nrf-hal#202]
Just noticed the `rtic-demo`example seems to break CI after the latest merge of the master branch?

**Comment by jonas-schievink** [comment]
Hmm, I've tried to reproduce this locally but it doesn't happen there (neither on master nor on your i2s branch).

**Comment by kalkyl** [comment]
Hmm, same here...

**Comment by jonas-schievink** [comment]
Ah, no, I had to delete `Cargo.lock`. This is a regression introduced by the latest RTIC release.

**Comment by kalkyl** [comment]
Ahh!

**Comment by jonas-schievink** [comment]
Filed https://github.com/rtic-rs/cortex-m-rtic/issues/351, looks like they're already working on a fix

**Comment by kalkyl** [comment]
Resolved!
