### ISSUE TITLE
gpio port not actually Floating

### ISSUE THREAD

**Issue by daschl** [nrf-rs/nrf-hal#213]
Hi,

I'm not sure if this is expected, but it at least looks "weird" to me. The issue is that my Input, even though marked as Floating, doesn't work out of the box, only if I call `into_floating_input` explicitly on it.

So, consider this code:

```rs
let peripherals = Peripherals::take().unwrap();
let port1 = p1::Parts::new(peripherals.P1);
let external_temp_sensor = Tsic::new(port1.p1_08.into_floating_input().degrade());
```

This work as expected (my `Tsic` takes `Pin<Input<Floating>>` as an argument). But if I do it like this, it compiles, but I'll never get the high and low states of the pin:

```rs
let peripherals = Peripherals::take().unwrap();
let port1 = p1::Parts::new(peripherals.P1);
let external_temp_sensor = Tsic::new(port1.p1_08.degrade());
```

Would it be possible that the port on the peripheral is neither `Floating`, nor `PullDown` or `PullUp` but it would always have to be turned `into` one of these types? This would make it explicit that it needs to be called, I couldn't figure out why my sensor didn't work and only stumbled on this by trial and error. Or is there something else going on that I'm missing?

**Comment by jonas-schievink** [comment]
Hmm, what does the datasheet say? Maybe not every pin starts in floating input mode?

**Comment by daschl** [comment]
@jonas-schievink I couldn't locate it in the datasheet. Sorry forgot to mention it's the 52840 DK and the pin I use is P1.08

**Comment by jonas-schievink** [comment]
Oh, I see the problem. The `PIN_CNF` registers are all initialized with `INPUT` set to `Disconnect`, so whatever is on the pin doesn't actually get sampled into the input buffer. Calling `into_floating_input` explicitly connects the input buffer.

**Comment by jonas-schievink** [comment]
This seems to be the case for *every* nRF chip. I wonder why nobody hit this before.

I think the proper fix would be to introduce a new "Disconnected" or "Reset" pin state and make every pin start in this state.

**Comment by jonas-schievink** [comment]
@daschl Can you try out https://github.com/nrf-rs/nrf-hal/pull/220? That should fix this issue.

**Comment by daschl** [comment]
I won’t be able to test it over the weekend, but next week I’ll give it a try. From looking at the change it makes a lot of sense to me.

**Comment by daschl** [comment]
Got it tested, works great - thanks!
