### ISSUE TITLE
GPIOTE task doesn't set gpio port, only pin.

### ISSUE THREAD

**Issue by Dirbaio** [nrf-rs/nrf-hal#238]
same as #216 but for task channel instead of event channel.
https://github.com/nrf-rs/nrf-hal/blob/22910ee8592c33b8c3e55891b6a5c7f953ab5e3a/nrf-hal-common/src/gpiote.rs#L364

**Comment by jonas-schievink** [comment]
Should be fixed by https://github.com/nrf-rs/nrf-hal/pull/248, closing
