### ISSUE TITLE
ieee802154 start_recv is unsound

### ISSUE THREAD

**Issue by Dirbaio** [nrf-rs/nrf-hal#310]
https://github.com/nrf-rs/nrf-hal/blob/master/nrf-hal-common/src/ieee802154.rs#L384

The user can start recv into a `&mut` buffer, deallocate it, and then have the radio DMA overwrite deallocated memory.

**Comment by jonas-schievink** [comment]
Yeah, seems like we should mark that as `unsafe`. It's internal (and private) though, so this should only be a minor bug.
