### ISSUE TITLE
Status of nRF5340 support

### ISSUE THREAD

**Issue by bogdanm** [nrf-rs/nrf-hal#362]
Hi, I've noticed that there is an `nrf5340` branch on this repository, but I don't know how complete the nRF5340 implementation is, or if there are any plans to merge it to master in the near future. If someone could clarify this it'd be helpful. Thank ou.

**Comment by jsosulski** [comment]
It seems the application core was added in https://github.com/nrf-rs/nrf-hal/pull/366 which is available on https://crates.io/crates/nrf5340-app-hal i.e.:

```toml
nrf5340-app-hal = "0.14.1"
```

**Comment by jonas-schievink** [comment]
[v0.15.1](https://github.com/nrf-rs/nrf-hal/releases/tag/v0.15.1) includes a HAL for both the Application and Network core, so closing this :tada:
