### ISSUE TITLE
nRF51822 Support

### ISSUE THREAD

**Issue by netthier** [nrf-rs/nrf-hal#367]
Hey, is any support for the nRF51822, used by the Calliope Mini, planned?
If not, how hard would it be to implement?

**Comment by jonas-schievink** [comment]
We don't currently have a PAC for that chip, so you'd have to add one to https://github.com/nrf-rs/nrf-pacs. Then, adding HAL support should be relatively straightforward (you can check https://github.com/nrf-rs/nrf-hal/pull/148 for an example PR adding support for a new chip).

**Comment by netthier** [comment]
Do you know where I could find the SVD file for that chip? I tried downloading the MDK, and while it does contain SVD's for a lot of chips, there are only the following, relatively short, files for the 51822:

- `nrf51822_peripherals.h`
- `nrf51822_xxaa.ld`
- `nrf51822_xxab.ld`
- `nrf51822_xxac.ld`

Furthermore, the header file contains the line
`/* This file is deprecated */`
How would I generate a PAC crate for this chip?

**Comment by jonas-schievink** [comment]
Oh, nRF5**1**822, that's already supported by the `nrf51-pac` and `nrf51-hal`. I thought it said nRF5**2**822, which does not seem to exist.

**Comment by netthier** [comment]
Ah, that's awesome. Thanks!
