### ISSUE TITLE
nrf51-hal on nightly

### ISSUE THREAD

**Issue by carnotweat** [nrf-rs/nrf-hal#484]
```
/home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nrf51-hal-0.5.2/src/lib.rs:4:12
4 | #![feature(const_fn)]
  |            ^^^^^^^^ feature has been removed
  |
  = note: split into finer-grained feature gates
```

**Comment by BartMassey** [comment]
Thanks for the report. Frustrating. Any chance you could figure this one out and post a pull request?

**Comment by qwandor** [comment]
`nrf51-hal` 0.5.2 is 6 years old and this was fixed a long time ago. Please update to a more recent version. 0.18.0 is the current version.
